### PR TITLE
Typing cleanup

### PR DESCRIPTION
**Pull request by A-UNDERSCORE-D**
Removes some deprecated things (subclassing `object`), updates annotations to 3.10 spec (and uses future imports to maintain compat with 3.7 -- I dont think there are any 3.6 issues here, but the future import is from 3.7)

Generally formatted all files with black

### CODE REVIEW

**Comment by jesopo** [comment]
could we save the reformatting for a separate PR :p

**Comment by A-UNDERSCORE-D** [comment]
bah habit >.>

**Comment by A-UNDERSCORE-D** [comment]
Sorry Ill try and redo this without reformatting everything. Its just easier for me to do as I go

**Comment by A-UNDERSCORE-D** [comment]
Would you prefer I did NO formatting changes at all, or just what black does?

**Comment by A-UNDERSCORE-D** [comment]
Actually let me do what I did on ircrobots, PR automated reformats *FIRST*, then we wont have noise otherwise

**Comment by A-UNDERSCORE-D** [comment]
closed in favor of https://github.com/jesopo/irctokens/pull/6

**Pull request closed without merging**
